image: "ruby:2.5"

cache:
  paths:
    - vendor/ruby
    - $HOME/.cargo

before_script:
  - [[ -f $HOME/.cargo/env ]] && curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source ~/.cargo/env
  - (cd ext/rure/regex-capi && cargo build --release)
  - ruby -v
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor --binstubs
  - bin/rake compile -- --with-rure-lib=$(pwd)/ext/rure/regex-capi/target/release

#rubocop:
#  script:
#  - rubocop

rspec:
  script:
  - bin/rspec